/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Dell' at '20/4/19 3:30 PM' with Gradle 3.0
 *
 * @author Dell, @date 20/4/19 3:30 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
