package com.org.ste.pojo;

// default package
// Generated 12 Oct, 2017 5:07:22 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * ProposalNonUlipNumSort generated by hbm2java
 */
@SuppressWarnings("serial")
public class ProposalNonUlipNumSort implements java.io.Serializable {

	private BigDecimal serialNo;
	private String nonUlipNo;

	public ProposalNonUlipNumSort() {
	}

	public ProposalNonUlipNumSort(BigDecimal serialNo) {
		this.serialNo = serialNo;
	}

	public ProposalNonUlipNumSort(BigDecimal serialNo, String nonUlipNo) {
		this.serialNo = serialNo;
		this.nonUlipNo = nonUlipNo;
	}

	public BigDecimal getSerialNo() {
		return this.serialNo;
	}

	public void setSerialNo(BigDecimal serialNo) {
		this.serialNo = serialNo;
	}

	public String getNonUlipNo() {
		return this.nonUlipNo;
	}

	public void setNonUlipNo(String nonUlipNo) {
		this.nonUlipNo = nonUlipNo;
	}

}
