package com.org.ste.pojo;

// default package
// Generated 12 Oct, 2017 5:07:22 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * ProposalUlipNumSort generated by hbm2java
 */
@SuppressWarnings("serial")
public class ProposalUlipNumSort implements java.io.Serializable {

	private BigDecimal serialno;
	private String ulipNo;

	public ProposalUlipNumSort() {
	}

	public ProposalUlipNumSort(BigDecimal serialno, String ulipNo) {
		this.serialno = serialno;
		this.ulipNo = ulipNo;
	}

	public BigDecimal getSerialno() {
		return this.serialno;
	}

	public void setSerialno(BigDecimal serialno) {
		this.serialno = serialno;
	}

	public String getUlipNo() {
		return this.ulipNo;
	}

	public void setUlipNo(String ulipNo) {
		this.ulipNo = ulipNo;
	}

}
