/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Sutar' at '5/10/19 11:56 PM' with Gradle 3.0
 *
 * @author Sutar, @date 5/10/19 11:56 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
