/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Sutar' at '5/8/19 10:25 PM' with Gradle 3.0
 *
 * @author Sutar, @date 5/8/19 10:25 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
