create table COLLEGE (
	COLLEGE_ID integer not null,
	COLLEGE_NAME varchar(12),
	COLLEGE_PINCODE integer not null,
	CONSTRAINT COLLEGE_PRIMARY_KEY PRIMARY KEY (COLLEGE_ID)
);

ALTER TABLE COLLEGE ALTER COLUMN COLLEGE_NAME varchar not null;

create table STUDENT (
	STUDENT_ID integer not null,
	STUDENT_NAME varchar(30) not null,
	COLLEGE_ID integer not null,
	CONSTRAINT STUDENT_PRIMARY_KEY PRIMARY KEY (STUDENT_ID),
	CONSTRAINT STUDENT_FOREIGN_KEY FOREIGN KEY (COLLEGE_ID) REFERENCES COLLEGE (COLLEGE_ID)
);

select * 
from student;

create table PROFESSOR (
	PROFESSOR_ID integer not null,
	PROFESSOR_NAME varchar(30) not null,
	COLLEGE_ID integer not null,
	PROFESSOR_BRANCH varchar(10) not null,
	CONSTRAINT PROFESSOR_PRIMARY_KEY PRIMARY KEY (PROFESSOR_ID),
	CONSTRAINT PROFESSOR_FOREIGN_KEY FOREIGN KEY (COLLEGE_ID) REFERENCES COLLEGE (COLLEGE_ID)
);

INSERT INTO COLLEGE VALUES(1,'ACE',101);

DELETE 
FROM COLLEGE 
WHERE COLLEGE_ID=1;

select * 
from COLLEGE;

INSERT INTO COLLEGE VALUES (1,'A',101);
INSERT INTO COLLEGE VALUES (2,'B',102);
INSERT INTO COLLEGE VALUES (3,'C',103);

INSERT INTO STUDENT VALUES (1,'kuntan',1);
INSERT INTO STUDENT VALUES (2,'gaurang',2);
INSERT INTO STUDENT VALUES (3,'ajay',3);

select * from student;

INSERT INTO PROFESSOR VALUES (1,'kanan',1,'IT');
INSERT INTO PROFESSOR VALUES (2,'kalekar',2,'CS');
INSERT INTO PROFESSOR VALUES (3,'durga',3,'EXTC');

select * from PROFESSOR;

select COLLEGE.COLLEGE_ID, COLLEGE.COLLEGE_NAME, STUDENT.STUDENT_NAME FROM COLLEGE INNER JOIN STUDENT ON COLLEGE.COLLEGE_ID=STUDENT.STUDENT_ID;

UPDATE PROFESSOR SET PROFESSOR_ID=4 WHERE PROFESSOR_NAME='kanan';