/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kuntan.sutar' at '25/4/19 11:42 AM' with Gradle 3.0
 *
 * @author kuntan.sutar, @date 25/4/19 11:42 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
