/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Dell' at '18/5/19 12:02 PM' with Gradle 3.0
 *
 * @author Dell, @date 18/5/19 12:02 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
